# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VideoManager < Formula
  desc 'CLI tool for downloading and managing videos'
  homepage 'https://github.com/caffeine-addictt/video-manager'
  version '0.0.6'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.6/video-manager_0.0.6_darwin_amd64.tar.gz'
      sha256 '790d745f5d4841ada23b3971bc0328c379579efefa66b5217eb6d53c1f7c9f2c'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.6/video-manager_0.0.6_darwin_arm64.tar.gz'
      sha256 '1ef21c5dacc38fc2439beb4b86385e8f8a8698716ef1c86346b30393009331a7'

      def install
        bin.install 'video-manager'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.6/video-manager_0.0.6_linux_amd64.tar.gz'
      sha256 'f7f666a13c7f6c2a72d85713cc100d3f4ee8cd83a4a1467a64fb7277df8a3f4f'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.6/video-manager_0.0.6_linux_arm64.tar.gz'
      sha256 '09d77bd4cacf01af66095d585bdbef5aa765e92405b1c5f0bc9657148e5ae571'

      def install
        bin.install 'video-manager'
      end
    end
  end
end
