# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VideoManager < Formula
  desc 'CLI tool for downloading and managing videos'
  homepage 'https://github.com/caffeine-addictt/video-manager'
  version '0.0.4'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.4/video-manager_0.0.4_darwin_amd64.tar.gz'
      sha256 '9e47768290c16441a84a2b72c92451f10dd58c3034ac04a2f0aa3da2f56b73e3'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.4/video-manager_0.0.4_darwin_arm64.tar.gz'
      sha256 '9c84cc05e53b440488dfbe974cdb147df7b2208e3a417e044f2ede5270368488'

      def install
        bin.install 'video-manager'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.4/video-manager_0.0.4_linux_amd64.tar.gz'
      sha256 '7284d598a16a23eac7d70b29c62076f2f06045d1fedf0d3c4a6a2da19a5675e5'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.4/video-manager_0.0.4_linux_arm64.tar.gz'
      sha256 'b1659fa238c5b211440c3de38d5c56f27a304a7acc15fcc4db7fc2a87b8333b3'

      def install
        bin.install 'video-manager'
      end
    end
  end
end
