# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VideoManager < Formula
  desc 'CLI tool for downloading and managing videos'
  homepage 'https://github.com/caffeine-addictt/video-manager'
  version '0.0.2'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.2/video-manager_0.0.2_darwin_amd64.tar.gz'
      sha256 'a5d7758ccebd72556e96b9569dc55b9495a739269261b1e205f6ad811b06bbcb'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.2/video-manager_0.0.2_darwin_arm64.tar.gz'
      sha256 '788a1444e5e8a34f1b9d043229a1743970a20c8e8882b92b4eafa3c58c542296'

      def install
        bin.install 'video-manager'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.2/video-manager_0.0.2_linux_amd64.tar.gz'
      sha256 '51eaed6e504aa23e246b0f0cb04aeb1eb787a3c6c7b67acdf1f3dd1896fe001c'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.2/video-manager_0.0.2_linux_arm64.tar.gz'
      sha256 '0cb1d4a1a9ecd21b952626dffacafd0d0b35e8032574200123010dd5900b0946'

      def install
        bin.install 'video-manager'
      end
    end
  end
end
