# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VideoManager < Formula
  desc 'CLI tool for downloading and managing videos'
  homepage 'https://github.com/caffeine-addictt/video-manager'
  version '0.0.5'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.5/video-manager_0.0.5_darwin_amd64.tar.gz'
      sha256 '68d65eabb7e56d434b97fecee0146785b0314915b7e15a85c721048a1e1d4e61'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.5/video-manager_0.0.5_darwin_arm64.tar.gz'
      sha256 'b419cba060f15dd939dd10eba7e032d1df0e2f994ce203a270330cfd10218401'

      def install
        bin.install 'video-manager'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.5/video-manager_0.0.5_linux_amd64.tar.gz'
      sha256 'cef24ddd46504a3d63324d797c3ee7e0f8673da2ceb13e0221ceca645dc2d1c7'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.5/video-manager_0.0.5_linux_arm64.tar.gz'
      sha256 '0f4f10f719a9de6432c9efa1721272d4e3720ac337439ab2305b5ea0f1594b34'

      def install
        bin.install 'video-manager'
      end
    end
  end
end
