# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VideoManager < Formula
  desc 'CLI tool for downloading and managing videos'
  homepage 'https://github.com/caffeine-addictt/video-manager'
  version '0.0.3'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.3/video-manager_0.0.3_darwin_amd64.tar.gz'
      sha256 'f86f2140a69fad21c08b9f5cdb3360637817cdc7bd29ccb8621a9fd6792d5bd3'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.3/video-manager_0.0.3_darwin_arm64.tar.gz'
      sha256 '08cd59d1d49d0c5865d5e87fd9deaa10a0f45f61e416cd9619d594ad22a395b0'

      def install
        bin.install 'video-manager'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.3/video-manager_0.0.3_linux_amd64.tar.gz'
      sha256 '592261299e38157083018b23a09a67d5607d2b336b2d2f1f674fbe36c8708845'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.3/video-manager_0.0.3_linux_arm64.tar.gz'
      sha256 '44e36e9840ac09b1b1f8493ca13db1213bb96abced35cb36146d5ae31b5c09a8'

      def install
        bin.install 'video-manager'
      end
    end
  end
end
