# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VideoManager < Formula
  desc 'CLI tool for downloading and managing videos'
  homepage 'https://github.com/caffeine-addictt/video-manager'
  version '0.0.1'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.1/video-manager_0.0.1_darwin_amd64.tar.gz'
      sha256 '7e33d1b97aa521a3ff57c35d8c7b6134e0cfa836dbd0e95aadb525f23a6168dc'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.1/video-manager_0.0.1_darwin_arm64.tar.gz'
      sha256 '240670dd37ff3c67ed239f4b5f38e0c28839de66d117cb3de1264a89861d5b7'

      def install
        bin.install 'video-manager'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.1/video-manager_0.0.1_linux_amd64.tar.gz'
      sha256 '1fbf1e56b34cf13da92c2176db0816f3886bb1a88605790f19ab4fa743e61c74'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.1/video-manager_0.0.1_linux_arm64.tar.gz'
      sha256 '6a9d7636d4b97010c5db8410fcffe9a01330b0f7fda9249330682d649f7fc92d'

      def install
        bin.install 'video-manager'
      end
    end
  end
end
