# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VideoManager < Formula
  desc 'CLI tool for downloading and managing videos'
  homepage 'https://github.com/caffeine-addictt/video-manager'
  version '0.0.7'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.7/video-manager_0.0.7_darwin_amd64.tar.gz'
      sha256 '37e11ebd72cb55eee4842add8fdf71e38be0f289a2fdaa97f5515599741be3c2'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.7/video-manager_0.0.7_darwin_arm64.tar.gz'
      sha256 '568eb83d4017c997c0d8154caee27c73e30229d6171644fc08e44bf0aac01cca'

      def install
        bin.install 'video-manager'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.7/video-manager_0.0.7_linux_amd64.tar.gz'
      sha256 '9e3d79c907c1af2869d6fd8d1bbbe19a87af44979928f22fadd855f1a942235c'

      def install
        bin.install 'video-manager'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.7/video-manager_0.0.7_linux_arm64.tar.gz'
      sha256 'b212a7221d5db4b275f08f88a6560280eb02164e0f8ad31cba3ce6d083eef11c'

      def install
        bin.install 'video-manager'
      end
    end
  end
end
