# This file was generated by GoReleaser. DO NOT EDIT.
cask "waku" do
  name "waku"
  desc "A simple template repository generator. Lets make starting new projects feel like a breeze again!"
  homepage "https://github.com/caffeine-addictt/waku"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waku"
  bash_completion "completions/waku.bash"
  zsh_completion "completions/waku.zsh"
  fish_completion "completions/waku.fish"
  depends_on cask: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/caffeine-addictt/waku/releases/download/v#{version}/waku_Darwin_x86_64.tar.gz"
      sha256 "3de9ead697006c77231b2776ddef2afcaba7f685c0543b91fe0f28adf25d4613"
    end
    on_arm do
      url "https://github.com/caffeine-addictt/waku/releases/download/v#{version}/waku_Darwin_arm64.tar.gz"
      sha256 "451c639cf7fdfa2dac91bbd5c095b99288fda023f778004483b0427dd387eaba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/caffeine-addictt/waku/releases/download/v#{version}/waku_Linux_x86_64.tar.gz"
      sha256 "59cd62021bff19db727657cdedf6c5e7a38c6b24fcda8912dba50bef967150dc"
    end
    on_arm do
      url "https://github.com/caffeine-addictt/waku/releases/download/v#{version}/waku_Linux_arm64.tar.gz"
      sha256 "c32d0af91f90cabe3b0f4a99c5574aad9ad338ea0018ec1eb70f70d3cdaedad4"
    end
  end

  # No zap stanza required
end
