# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waku < Formula
  desc "A simple template repository generator. Lets make starting new proejcts feel like a breeze again!"
  homepage "https://github.com/caffeine-addictt/waku"
  version "0.2.3"
  license "AGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.2.3/waku_0.2.3_darwin_amd64.tar.gz"
      sha256 "79462aa2a032fc562b0e05d8194b6076c04b4c8de89f16c034b75ff074271f31"

      def install
        bin.install "waku"
      end
    end
    on_arm do
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.2.3/waku_0.2.3_darwin_arm64.tar.gz"
      sha256 "eb2c1c68a380718f66ee1783828f97c9adec67d6d6d43e558816b9eba549719c"

      def install
        bin.install "waku"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.2.3/waku_0.2.3_linux_amd64.tar.gz"
        sha256 "176139c2bc12e26dde3ffd0ef1baad94a2c7cf1a048cb91e711526096d7731b5"

        def install
          bin.install "waku"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.2.3/waku_0.2.3_linux_arm64.tar.gz"
        sha256 "c752d11691291649d68518e5bafcfec0a02caf6a71252befb1b5fbc2de7263c1"

        def install
          bin.install "waku"
        end
      end
    end
  end
end
