# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waku < Formula
  desc "A simple template repository generator. Lets make starting new proejcts feel like a breeze again!"
  homepage "https://github.com/caffeine-addictt/waku"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.1.0/waku_0.1.0_darwin_amd64.tar.gz"
      sha256 "b03f00d077610d8f90374bdea6d1bd455113f36860b57ccd85accb8ce6ae6b8d"

      def install
        bin.install "waku"
      end
    end
    on_arm do
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.1.0/waku_0.1.0_darwin_arm64.tar.gz"
      sha256 "0ff92aa12a2ed6e1db9e791c53e910696d7cc1f602d412728df505098bab70aa"

      def install
        bin.install "waku"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.1.0/waku_0.1.0_linux_amd64.tar.gz"
        sha256 "e03485f88d2e2b7becd41d8bb68f46bf4993c7475d94a5d886ff01bff340e8f7"

        def install
          bin.install "waku"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.1.0/waku_0.1.0_linux_arm64.tar.gz"
        sha256 "e6460f0e40505a9e45acd78fae29f6ceb56e0bc00f75381fbf0b25a017a603bd"

        def install
          bin.install "waku"
        end
      end
    end
  end
end
