# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waku < Formula
  desc "A simple template repository generator. Lets make starting new projects feel like a breeze again!"
  homepage "https://github.com/caffeine-addictt/waku"
  version "0.8.1"
  license "AGPL-3.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.8.1/waku_Darwin_x86_64.tar.gz"
      sha256 "51d6858a6d5e3ce902a514ef6c065f26025a8b8aa5bffacaa3668a36924fb553"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.8.1/waku_Darwin_arm64.tar.gz"
      sha256 "115c1773842919eef98dbafdd149b575a40d887161dd6a41b87b64c36bafaf81"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.8.1/waku_Linux_x86_64.tar.gz"
        sha256 "0a08ab02391b3fa5c08ac96745d6c5b3add271d6a21d1d581358b480db538173"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.8.1/waku_Linux_arm64.tar.gz"
        sha256 "999237da0b1996eab9db251622ea062c6b5089577ababfdd3ae2e5517cf18ca8"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/waku version"
  end
end
