# This file was generated by GoReleaser. DO NOT EDIT.
cask "waku" do
  name "waku"
  desc "A simple template repository generator. Lets make starting new projects feel like a breeze again!"
  homepage "https://github.com/caffeine-addictt/waku"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "waku"
  bash_completion "completions/waku.bash"
  zsh_completion "completions/waku.zsh"
  fish_completion "completions/waku.fish"
  depends_on cask: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/caffeine-addictt/waku/releases/download/v#{version}/waku_Darwin_x86_64.tar.gz"
      sha256 "4357e2dddbe7dce971f98a21e06338afb5a9c68df8e734800e86beb52051a442"
    end
    on_arm do
      url "https://github.com/caffeine-addictt/waku/releases/download/v#{version}/waku_Darwin_arm64.tar.gz"
      sha256 "670d7c6811b2b75fbf9d0f8b8285878957aa39e76caa870a0cfcf8db1cdf960f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/caffeine-addictt/waku/releases/download/v#{version}/waku_Linux_x86_64.tar.gz"
      sha256 "5d8e895ef80bc05772fee6c9273c80ba891b4361d1ab2e33a7a867373c862702"
    end
    on_arm do
      url "https://github.com/caffeine-addictt/waku/releases/download/v#{version}/waku_Linux_arm64.tar.gz"
      sha256 "9337fc8c29b5a08f6202a850b83f0c0c4c9b9d04e09ac981c523a2d561083278"
    end
  end

  # No zap stanza required
end
