# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waku < Formula
  desc "A simple template repository generator. Lets make starting new proejcts feel like a breeze again!"
  homepage "https://github.com/caffeine-addictt/waku"
  version "0.3.1"
  license "AGPL-3.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.3.1/waku_Darwin_x86_64.tar.gz"
      sha256 "72736a17cb371ef72f043ec1ca35b9d174f2abb8cd9800cd1f83cb623a5108df"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
    on_arm do
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.3.1/waku_Darwin_arm64.tar.gz"
      sha256 "f8888a4f5d4360aa08fd3509a7a8e321932bb02a424550ed1362ca54c3f5f15b"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.3.1/waku_Linux_x86_64.tar.gz"
        sha256 "7c9e24b8cd46cf985f1a268248a17b18a38afab86d59bd86b0af5f239d5d0899"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.3.1/waku_Linux_arm64.tar.gz"
        sha256 "63d6e4042479fc4bb2128cb399536ed755f995565675791fc84253e30b189bc3"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/waku version"
  end
end
