# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waku < Formula
  desc "A simple template repository generator. Lets make starting new projects feel like a breeze again!"
  homepage "https://github.com/caffeine-addictt/waku"
  version "0.9.1"
  license "AGPL-3.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.9.1/waku_Darwin_x86_64.tar.gz"
      sha256 "740a9991786df7a5a207a8176bcdba630173b7474a93a62bfd572f706740339b"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.9.1/waku_Darwin_arm64.tar.gz"
      sha256 "2b32cb8185a21cb92f1d87439a661aa9665ecfe757f0bc1267a802a815686287"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.9.1/waku_Linux_x86_64.tar.gz"
        sha256 "2cd05c610b7f5e1a564ba5765f90cbe61ddb5f80f9a53c19b6a852814f3624b3"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.9.1/waku_Linux_arm64.tar.gz"
        sha256 "0a8eb62d9e04085499e24836f4267bf750d59f684fa55ffd9f3788be4549692c"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/waku version"
  end
end
