# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waku < Formula
  desc "A simple template repository generator. Lets make starting new projects feel like a breeze again!"
  homepage "https://github.com/caffeine-addictt/waku"
  version "0.3.3"
  license "AGPL-3.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.3.3/waku_Darwin_x86_64.tar.gz"
      sha256 "dacdfdb222bf76ff7ae2b909d3ca8bbc39133328f53ddcb03aad37a6813eaef6"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
    on_arm do
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.3.3/waku_Darwin_arm64.tar.gz"
      sha256 "8e531a9160b558aa661935e9178322a0037cc8f8e474be209608dc26b54bf2f1"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.3.3/waku_Linux_x86_64.tar.gz"
        sha256 "8541e0315748ac67db355e82305718e72306ddedcba3b3716977f8f9046dadde"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.3.3/waku_Linux_arm64.tar.gz"
        sha256 "c5203d57ffbe149c52288733bbcb6628b0b7bc00b5b59e7f747a85caaebcb0f1"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/waku version"
  end
end
