# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waku < Formula
  desc "A simple template repository generator. Lets make starting new projects feel like a breeze again!"
  homepage "https://github.com/caffeine-addictt/waku"
  version "0.9.2"
  license "AGPL-3.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.9.2/waku_Darwin_x86_64.tar.gz"
      sha256 "5d253f651e86413acc33ad90f26a00727d5dc0af94092692cbe74809532a77f7"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caffeine-addictt/waku/releases/download/v0.9.2/waku_Darwin_arm64.tar.gz"
      sha256 "26077267048ef768eaf7fdd4ce3bfe4cb4f8eb96652ba144195c27a222dd825c"

      def install
        bin.install "waku"
        bash_completion.install "completions/waku.bash" => "waku"
        zsh_completion.install "completions/waku.zsh" => "_waku"
        fish_completion.install "completions/waku.fish"
        man1.install "manpages/waku.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.9.2/waku_Linux_x86_64.tar.gz"
        sha256 "50b61b5671fd09ed60a711a2f4290ba9c2a6f6c3bd8d210f7ce0a175fce28791"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/caffeine-addictt/waku/releases/download/v0.9.2/waku_Linux_arm64.tar.gz"
        sha256 "d5f0a017050a08e75d90801949bcb6136eb7ad2e54c6255e6162a739327a3bb2"

        def install
          bin.install "waku"
          bash_completion.install "completions/waku.bash" => "waku"
          zsh_completion.install "completions/waku.zsh" => "_waku"
          fish_completion.install "completions/waku.fish"
          man1.install "manpages/waku.1.gz"
        end
      end
    end
  end

  test do
    system "#{bin}/waku version"
  end
end
