# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VideoManager < Formula
  desc "CLI tool for downloading and managing videos"
  homepage "https://github.com/caffeine-addictt/video-manager"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.5/video-manager_0.0.5_darwin_amd64.tar.gz"
      sha256 "5138ebb5cb7a37458c563fa0115ae41a072a7052a14114cc524d7dcb3e6e5446"

      def install
        bin.install "video-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.5/video-manager_0.0.5_darwin_arm64.tar.gz"
      sha256 "7abc79f2974eee2762f59e3b3ef912f30b9940b6abf313ea0a143123b131aad2"

      def install
        bin.install "video-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.5/video-manager_0.0.5_linux_amd64.tar.gz"
      sha256 "b851469e1829c65df3e29e1f42cb0e664ef6bc88ff837e871a2bc9a26e23eed8"

      def install
        bin.install "video-manager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caffeine-addictt/video-manager/releases/download/v0.0.5/video-manager_0.0.5_linux_arm64.tar.gz"
      sha256 "864805ca0d05ae56f8e7a6b0eaa997745b29c039b4490ea2aa2d1975766308b6"

      def install
        bin.install "video-manager"
      end
    end
  end
end
