name: Versioner
on:
  push:
    paths:
      - "Formula/**"
    branches-ignore:
      - main

jobs:
  version:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git --global user.name 'github-actions[bot]'
          git --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Diff
        run: |
          # Only care about Formula/<same>/<same>.rb
          CHANGED=$(git diff --name-only main | grep -E 'Formula/([^/]+)/\1\.rb' || echo "")

          if [ -z "$CHANGED" ]; then
            echo "No matching formulas detected."
            exit 0
          fi

          echo "CHANGED=${CHANGED}" >> $GITHUB_ENV

      - name: Auto version formulas
        if: env.CHANGED != ""
        run: |
          for FORMULA_PATH in $CHANGED; do
            FORMULA_NAME=$(basename "$FORMULA_PATH" .rb)
            VERSION=$(grep -Eo 'version\s+"[0-9.]+"' "${FORMULA_PATH}" | awk '{print $2}' | tr -d '"')
            MAJOR_VERSION=$(echo "${VERSION}" | cut -d. -f1)
            TAG=$(echo "${VERSION}" | sed 's/^v//')
            IS_PRERELEASE=$(echo "${VERSION}" | grep -E '[-a-zA-Z]')

            echo "Processing formula: ${FORMULA_NAME}, Version: ${VERSION}, Major Version: ${MAJOR_VERSION}, Tag: ${TAG}"

            # major Formula/name/name@X.rb
            if [ -z "${IS_PRERELEASE}" ]; then
              echo "Skipping major version as it is a prerelease version."
            else
              echo "Creating new major version for ${FORMULA_NAME}."
              cp "${FORMULA_PATH}" "Formula/${FORMULA_NAME}/${FORMULA_NAME}@${MAJOR_VERSION}.rb"
            fi

            # full Formula/name/name@X.X.X.*.rb
            echo "Creating new full version for ${FORMULA_NAME}."
            cp "${FORMULA_PATH}" "Formula/${FORMULA_NAME}/${FORMULA_NAME}@${TAG}.rb"
          done

      - name: Commit versioned formulas
        if: env.CHANGED != ''
        run: |
          git commit -m "Auto versioned formula(s): ${{ env.CHANGED }}"

      - name: Push
        if: env.CHANGED != ''
        run: |
          git push origin "${GITHUB_REF##*/}"

      - name: PR to main
        if: env.CHANGED != ''
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "${GITHUB_REF##*/}"
          title: "feat: auto versioned formula"
          body: |
            THis PR was auto generated by a workflow to
            automatically version the following formula(s):

            `${{ env.CHANGED }}`
          reviewers: caffeine-addictt
