name: Versioner
on:
  push:
    paths:
      - "Formula/**"
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  version:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Diff
        run: |
          # Only care about Formula/<same>/<same>.rb
          CHANGED=$(git diff --name-only origin/main | grep -E 'Formula/([^/]+)/\1\.rb' || echo "")

          if [ -z "$CHANGED" ]; then
            echo "No matching formulas detected."
            exit 0
          fi

          echo "CHANGED=${CHANGED}" >> $GITHUB_ENV

      - name: Auto version formulas
        if: env.CHANGED
        run: |
          set -xe -o pipefail
          for FORMULA_PATH in $CHANGED; do
            FORMULA_NAME=$(basename "$FORMULA_PATH" .rb)
            VERSION=$(grep -Eo 'version\s+"[0-9.]+"' "${FORMULA_PATH}" | awk '{print $2}' | tr -d '"')
            MAJOR_VERSION=$(echo "${VERSION}" | cut -d. -f1 || echo "")
            IS_STABLE=$(echo "${VERSION}" | grep -E '[-a-zA-Z]' || echo "")

            echo "Processing formula: ${FORMULA_NAME}, Version: ${VERSION}, Major Version: ${MAJOR_VERSION}, Stable?: ${IS_STABLE}."

            # major Formula/name/name@X.rb
            if [ -z "${IS_STABLE}" ]; then
              echo "Creating new major version for ${FORMULA_NAME}."
              cp "${FORMULA_PATH}" "Formula/${FORMULA_NAME}/${FORMULA_NAME}@${MAJOR_VERSION}.rb"
            else
              echo "Skipping major version as it is a prerelease version."
            fi

            # full Formula/name/name@X.X.X.*.rb
            echo "Creating new full version for ${FORMULA_NAME}."
            cp "${FORMULA_PATH}" "Formula/${FORMULA_NAME}/${FORMULA_NAME}@${VERSION}.rb"
          done

      - name: Commit versioned formulas
        if: env.CHANGED
        run: |
          git add Formula
          git commit -m "Auto versioned formula(s): ${{ env.CHANGED }}"

      - name: Push
        if: env.CHANGED
        run: |
          git push origin "${GITHUB_REF##*/}"

      - name: PR to main
        if: env.CHANGED
        run: |
          gh pr create -B main -H "${{ github.ref_name }}" --title 'feat: auto versioned formula' --body "${{ env.CHANGED }}" --reviewer caffeine-addictt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
